version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
          - php
        networks:
            - gaffa-network

    php:
        build: .
        volumes:
            - .:/data
        networks:
            - gaffa-network

networks:
    gaffa-network:
        driver: bridge